### ISSUE TITLE
Platform and UX Improvements

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#1919]
Having launched Kanaria, I realized how many UX hurdles we still have as normies tried to get on board. Here are the critical parts we need to handle:

- Wiki simple-guides are definitely needed, people are confused by:
  - making an account
  - wallet support
  - per-chain account settings
  - setting an identity
  - verifying an identity

These are just the basics, can't even imagine how it would be if they'd tried to stake etc.

So with that in mind, here's a plan:

- [ ] Create a simple IPFS-based UI for registering and verifying identities on Kusama and Polkadot
- [ ] Create a simple IPFS-based UI for switching account formats and other helping tools (similar to Shawn's helper tools)
- [x] Speed up the #1692 Guide process, focusing on the following first:
  - [x] What is Polkadot / Kusama?
  - [ ] What is Substrate?
  - [x] Making an account
  - [x] Setting up an identiy
  - [x] Verifying an identity
  - [x] How to nominate

I would like to also do the following:

- register a new domain for W3F-made tools
- set up IPNS links to it with DNSlink (have explored and implemented this option, is simple)
- build official UIs and tools to help people get through the initial hurdles (like the aforementioned UI for registering and verifying identities)
- host them on IPFS via this domain, so people can hit ipfs.io/ipns/identity.w3f.tools or something similar
- maintain these tools as a team, so each of us remains familiar with the implementations and keeps honing their Polkadot-interaction skills

All this would:

- reduce support tickets
- increase UX across the board
- take the load off of Jaco and the Polkadot JS Apps UI (i.e. no way to request judgement smoothly, and unlikely to happen soon)
- provide us with unique insight into bottlenecks

This is a big and ambitious process, but I think it can have an enormous payoff, especially as new users come in post auction and parachain launch.

**Comment by salmad3** [comment]
All good suggestions, I would advocate that this [issue](https://github.com/w3f/polkadot-wiki/issues/1569) can be represented here to have one place of discussion.

Needs some planning. At the moment, we can focus on staging the changes in: https://github.com/w3f/polkadot-wiki/pull/2392

**Comment by salmad3** [comment]
## Proposal: Enhanced Interact Guides
### Current Look

#### Polkadot Wiki: 
![image](https://user-images.githubusercontent.com/25497083/138018397-bce20880-079a-468b-8e8f-fcb3d21ed65b.png)

#### Kusama Guide:
![image](https://user-images.githubusercontent.com/25497083/138018355-ef9857df-8d7d-4f49-9029-9aec490fe18e.png)

### Things to Consider:
- Enhanced design
- Enhanced usability
- "One-stop shop" for all the basics of the network

**Comment by salmad3** [comment]
Pending Polkadot Brand-wide update.

**Comment by salmad3** [comment]
Considering our intent to do a complete revamp, this can be captured in a future master issue. Please reopen if otherwise.
