### ISSUE TITLE
Wiki-Ops

### ISSUE THREAD

**Issue by salmad3** [w3f/polkadot-wiki#2294]
## Workflows
 - [x] Enhance jobs and configuration files
    - build and deploy.
    - ~Substrate version check: https://github.com/w3f/polkadot-wiki/issues/1815~ Resolved in: https://github.com/w3f/polkadot-wiki/issues/2330
    - jobs should be swift and concise where they can be.
  - [x] Fix CI/CD substrate rustdoc link updater
    - master CICD should only fail if there is a build error
  - [x] Clean-up previous CircleCI implementation
 - [x] Stage non-prod versions off of main branch. 
 - ~[x] Fix Prettier~
 - ~[ ] Run Prettier on external PRs: https://github.com/w3f/polkadot-wiki/issues/944~ Using `pretty-quick` instead 
 - ~[ ] Abstract stalecheck: https://github.com/w3f/polkadot-wiki/issues/1064~
   - ~should also have a stale checker for older issues along with current stale checker for docs, and check for duplicate issues before creating an issue.~ -> instead of this updating in this manner, issues can be managed using a kanban board (`ZenHub` has been setup, can add with https://www.zenhub.com/extension). 
 - [x] updating the wiki results in all wiki pages mentioning the individual that committed recently - should only be those pages that were updated: https://github.com/w3f/polkadot-wiki/issues/2452

## Version 2
- [x] Fix link issue: https://github.com/w3f/polkadot-wiki/issues/2250
   team attempts thus far:
  - play around with config.
  - disable crowdin: https://github.com/w3f/polkadot-wiki/pull/2221
  - disable trailing slash: https://github.com/w3f/polkadot-wiki/pull/2281
  -  referencing update for possible docusaurus compatibility: https://github.com/w3f/polkadot-wiki/pull/2278
- [x] Naming convention
- [x] Injections: https://github.com/w3f/polkadot-wiki/issues/2443
- [x] Conversion tool: https://github.com/w3f/polkadot-wiki/issues/2415
  - configuration & reformatting? 

## Suggestions
  - [x] Create sub-directories for "docs" instead of having all wiki pages under one directory. (i.e.  `learn` has learn guides, `build` has build guides, etc.)
  - [x] Need to clean up repo in general - docker related files, configuration files, duplicates, etc.
  - ~[ ] Doc images could use a name convention and also organized into better sub-directories.~ I would say this can be revisited, but perhaps not a priority atm.
  - [x] Update README
  - [x] Community engagement and new members would benefit from "good first issues" (a label), such as: https://github.com/w3f/polkadot-wiki/issues/2298. 

Feel free to add/edit/refute and discuss these points.

**Comment by nam-hle** [comment]
I know it's quite early but removing the old `website` and `kusama-guide` folders could be added. 
Also, update `README.md`.

**Comment by jakehemmerle** [comment]
Readme says master is also pushed to IPFS by github actions but this doesn't seem correct. Should we add a new action to push new masters to IPFS?

**Comment by salmad3** [comment]
There's no CircleCI workflows that still run behind the scenes, right?

**Comment by salmad3** [comment]
Whenever anyone gets the chance, can you double check if the links are okay now? I have noticed one thing - when I first access the wiki (any page that is), for a split second it hits "page not found" but redirects.

This also happens until refreshing a few times:
![image](https://user-images.githubusercontent.com/25497083/125346633-fcd55080-e327-11eb-8f15-4fb8353df869.png)

**Comment by jakehemmerle** [comment]
> There's no CircleCI workflows that still run behind the scenes, right?

don't think so  (no .circleci folder), also couldn't find a login for it.

**Comment by salmad3** [comment]
> Readme says master is also pushed to IPFS by github actions but this doesn't seem correct. Should we add a new action to push new masters to IPFS?

@jakehemmerle https://github.com/w3f/polkadot-wiki/issues/696

**Comment by salmad3** [comment]
Brief update:
- cleaned up branches
- there is a branch called `v1` that would hold version 1 (& arguably a snapshot of version 2)
- another branch called `wikiops` that attempts to address... wikiops:) (merges to master)
- another branch could then serve as a `dev` or `test` for staging

**Comment by jakehemmerle** [comment]
> * there is a branch called `v1` that would hold version 1 (& arguably a snapshot of version 2)

I don't think there is any benefit of sustaining v1 as a separate branch as it just overcomplicates every `docs/` edit we make (since we have to open 2 prs; one to merge to `v1` and one for `v2`.) I don't think we should touch anything related to docusaurusv1 yet, but when we do, the only thing we should do it remove it from the repo. With that said, there are higher priority things than removing v1 from the codebase I think we should focus on (translation issues, redirect problems, dev server, etc), as having v1 in the codebase doesn't add any additional overhead to anything.

> A general approach could be:
> i. `wikiops` gets merged to `master`
> ii. change `wikiops` to `dev` - dev is used for staging/testing
> iii. clean up `v1`

i. what is the point of having `wikiops` as a seperate branch? it seems to just delay new things getting added to master/dev. As each thing comes up, it should get merged in immediately after approval from team members.
ii. why do we change `wikiops` to `dev` instead of just creating a new branch off of master? I think separating dev and prod is important, but a simple `master` -> deploy to dev server, and `prod` -> deploy to prod (with rule that the only way things get added to `prod` is via a PR merging `master` into `prod`) should suffice (unless you really want a `dev` branch, in which case we always merge `master` into `dev` and never commit directly on `dev` just like we would do with `master` and `prod`.) 

@emresurmeli @DrW3RK can I get your input as well?

**Comment by salmad3** [comment]
@jakehemmerle 
- `v1` doesn't have to hold any static docs or actual wiki content - just web related files. Up until version 2 is good it can serve as a backup. It's also not being prioritized over other issues.
- `wikiops` is just a branch to address some of these issues. 
- Regarding `master`, `prod`, `dev` - my mistake, I wrote it out incorrectly.  But I don't think `master` -> staging -> `prod` is necessary. What I meant to get at was: staging -> `master` (prod). `dev` wasn't the right name, more like `qa`, which would used for staging. PRs opened against `qa` -> stage and check, then  -> `master` (acts as prod), and qa would created against master.

**Comment by jakehemmerle** [comment]
> * `v1` doesn't have to hold any static docs or actual wiki content - just web related files. Up until version 2 is good it can serve as a backup. It's also not being prioritized over other issues.

Cool we are on the same page. This was my point; we shouldn't touch v1 or move it out of master until we go to delete it, otherwise if do anything special with it (like removing it from master and keeping it in another branch or anything), and we need to do use it, we can't easily rebase it, we have to deal with all the CICD related overhead to make v1 run and then any structural changes (like doc and config stuff) that would need to get fixed manually

**Comment by salmad3** [comment]
You're right. Also realized the wikiops branch idea and trying to outpace updates to master isn't a good idea haha. The motive behind it was to "clean up" the repo, but also because as right now, both versions are submerged together - for instance, updating the README to specify "polkadot2" and "kusama2" instead of "polkadot" and "kusama", respectively, because of both being accounted for in the package.json, doesn't seem reasonable

**Comment by jakehemmerle** [comment]
@DannyS03 I agree that naming should be consistant; what do you say we swap out `polkadot` for `polkadot1` and `polkadot2` for `polkadot`? That would mainly just be the `package.json` file and the CICD actions right?

**Comment by salmad3** [comment]
That sounds good. Right those should only be the things to update

**Comment by salmad3** [comment]
Folder structure should be prioritized: https://github.com/w3f/polkadot-wiki/issues/2415#issuecomment-892019159

**Comment by salmad3** [comment]
@nam-hle https://github.com/w3f/polkadot-wiki/pull/2442#issuecomment-895717581, any suggestions would be much appreciated

**Comment by salmad3** [comment]
@nam-hle it seems like injections still aren't getting recognized, for instance: https://wiki.polkadot.network/docs/learn-identity

**Comment by nam-hle** [comment]
Hi @DannyS03, as I said before, the Markdown parser misunderstood between our variable underscore and italic one. It can be fixed easily by changing italic underscore to asterisk. But I suggest to use camel convention for our variable to fix the issue permanently. What do you think?

**Comment by salmad3** [comment]
It seems like we've tackled the immediate tasks related to "wikiops" up until this point, where IPFS related tasks has an issue of its own that is tracking progress. Because of recent updates we have encountered redirect conflicts (being warnings more than anything), which is also tracked by more than one issue at the moment.
