### ISSUE TITLE
Audit and Update Parachain Content

### ISSUE THREAD

**Issue by salmad3** [w3f/polkadot-wiki#2692]
- [x] Ensure content is up-to-date.
  - [x] Build with Polkadot: https://github.com/w3f/polkadot-wiki/pull/2630
  - [x] Parachains: https://github.com/w3f/polkadot-wiki/pull/2710
  - [x] Parathreads: https://github.com/w3f/polkadot-wiki/pull/2710
  - [x] Bridges: https://github.com/w3f/polkadot-wiki/pull/2710
  - [x] Common Good Parachains: https://github.com/w3f/polkadot-wiki/pull/2710
  - [x] Parachain slot auctions: https://github.com/w3f/polkadot-wiki/pull/2710
  - [x] Parachain crowdloans: https://github.com/w3f/polkadot-wiki/pull/2710
  - [x] Teleporting Assets
  - [x] Parachain Development Guide: https://github.com/w3f/polkadot-wiki/pull/2630
- ~[x] Enhance Parachain Implementers Guide~ (merged into development guide): https://github.com/w3f/polkadot-wiki/pull/2630

- Idea: Categorize the *parachains*, *parathreads* and *bridges* learn docs under a **Para-objects** sub-heading, and put  the *parachain content* under a **Parachain** sub-heading; idea shown in markdown:

```
# Learn

## Paraobjects

### Parachains
#### Parachains
#### Common Good Parachains
#### Parachain Slot Auctions
#### Parachain Crowdloans

### Parathreads

### Bridges
```
Proposed in: https://github.com/w3f/polkadot-wiki/pull/2705

**Comment by salmad3** [comment]
Updates merged. Will review content periodically.
