### ISSUE TITLE
Polkadot Wiki Revamp

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#2941]
The key focus areas of the Wiki revamp are:

1. Organizational structure of Wiki docs
2. Update outdated content
3. Accessibility (light and dark mode, desktop and mobile)
4. Ease of search and SEO
5. Improved image assets and infographics
6. Identifying missing and good to have content (relevant for 1KC)
7. Cross-linking with Polkadot support pages

**To-do**

- [ ] https://github.com/w3f/wiki/issues/5
- [ ] https://github.com/w3f/wiki/issues/23
- [ ] https://github.com/w3f/wiki/issues/1

**Needs Input**

- [ ] https://github.com/w3f/wiki/issues/6
