### ISSUE TITLE
Videos request

### ISSUE THREAD

**Issue by michalisFr** [w3f/polkadot-wiki#3517]
A "short" list of video tutorials in no specific order.

- [ ] [The Roles & Responsibilities of a Validator](https://support.polkadot.network/support/solutions/articles/65000119415-the-roles-responsibilities-of-a-validator) (update)
- [ ] [How to claim your DOT - Tutorial](https://support.polkadot.network/support/solutions/articles/65000138217-how-to-claim-your-dot-tutorial) (update)
- [x] [How to restore your DOT account in Parity Signer](https://support.polkadot.network/support/solutions/articles/65000167901-how-to-restore-your-dot-account-in-parity-signer) ✅ --> https://youtu.be/hgv1R9mPEXw
- [x] [What is the "Existential Deposit"?](https://support.polkadot.network/support/solutions/articles/65000168651-what-is-the-existential-deposit-) & [Error: "balances.transferKeepAlive"](https://support.polkadot.network/support/solutions/articles/65000169248-i-can-t-send-funds-because-of-the-message-balances-transferkeepalive-what-should-i-do-) (update) ✅ --> https://youtu.be/mgPHVztHJWk
- [x] [How to switch network nodes](https://support.polkadot.network/support/solutions/articles/65000169778-how-to-switch-network-nodes-from-polkadot-to-kusama-or-v-v-) (update) ✅ -> https://www.youtube.com/watch?v=thj4dIMB5A8
- [x] [Why can't I transfer tokens?](https://support.polkadot.network/support/solutions/articles/65000169437-why-can-t-i-transfer-tokens) (update) ✅ -> https://youtu.be/LHgY7ds_bZ0
- [x] [How can I see if I'm in the top 128 nominators of an oversubscribed validator?](https://support.polkadot.network/support/solutions/articles/65000169392-how-can-i-see-if-i-m-in-the-top-64-nominators-of-an-oversubscribed-validator-)
[How can I unstake my tokens again?](https://support.polkadot.network/support/solutions/articles/65000167902-how-can-i-unstake-my-tokens-again-)
[How can I see my staking rewards?](https://support.polkadot.network/support/solutions/articles/65000168954-how-can-i-see-my-staking-rewards-)
[What does active / inactive / waiting mean?](https://support.polkadot.network/support/solutions/articles/65000169209-what-does-active-inactive-waiting-mean-)
[How can I bond more tokens to increase my stake?](https://support.polkadot.network/support/solutions/articles/65000169753-how-can-i-bond-more-tokens-to-increase-my-stake-)
[How do I change my validators?](https://support.polkadot.network/support/solutions/articles/65000170911-how-do-i-change-my-validators-)
[How can I see when my DOT tokens will be unlocked?](https://support.polkadot.network/support/solutions/articles/65000170076-how-can-i-see-when-my-dot-tokens-will-be-unlocked-)
[How to rebond tokens during the unbonding period](https://support.polkadot.network/support/solutions/articles/65000170241-how-to-rebond-tokens-during-the-unbonding-period)
[How can I change the destination account of my staking rewards?](https://support.polkadot.network/support/solutions/articles/65000173734-how-can-i-change-the-destination-account-of-my-staking-rewards-)
[How to change your controller account](https://support.polkadot.network/support/solutions/articles/65000175404-how-can-i-change-my-controller-account-)
A single video addressing all things "after staking" and we can link to specific timestamps of the video in each article.   ✅ --> https://youtu.be/58pIe8tt2o4
- [x] using https://staking.polkadot.network/dashboard/#/overview for Nominating ✅ --> https://youtu.be/F59N3YKYCRs
- [x] using the dashboard to join a pool ✅ --> https://youtu.be/dDIG7QAApig (Filippo's addition)
- [x] dashboard walkthrough ✅ --> https://youtu.be/hvXLc4H7rA4 (Filippo's addition)
- [x] [How to restore your Account in the Polkadot extension](https://support.polkadot.network/support/solutions/articles/65000169952-how-to-restore-your-account-in-the-polkadot-extension)  ✅ --> https://youtu.be/9ohp8k4Hz8c
- [x] [How to restore your Account in the Polkadot-JS UI](https://support.polkadot.network/support/solutions/articles/65000180110-how-to-restore-your-account-in-polkadot-js-ui) ✅ --> https://youtu.be/cBsZqFpBANY
- [x] [How to send / transfer funds out of your DOT account on the Polkadot-JS UI](https://support.polkadot.network/support/solutions/articles/65000170304-how-to-send-transfer-funds-out-of-your-dot-account-on-polkadot-js)
[How can I see the transaction costs before I make a transfer?](https://support.polkadot.network/support/solutions/articles/65000170292-how-can-i-see-the-transaction-costs-before-i-make-a-transfer-)
[How to send all of your funds out of your account](https://support.polkadot.network/support/solutions/articles/65000170293-how-to-send-all-of-your-funds-out-of-your-account)
[How to Send DOT from your Ledger Account on Polkadot-JS UI](https://support.polkadot.network/support/solutions/articles/65000181872-how-to-send-dot-from-your-ledger-account-on-polkadot-js-ui)
A single video for sending funds from all types of accounts ✅ --> https://youtu.be/gbvrHzr4EDY

- [x] [Ledger Error: Txn version not supported](https://support.polkadot.network/support/solutions/articles/65000176738-ledger-error-txn-version-not-supported)
[Ledger Error: "Unable to create enum via index"](https://support.polkadot.network/support/solutions/articles/65000178187-ledger-error-unable-to-create-enum-via-index-)
[Ledger Error: Spec version not supported](https://support.polkadot.network/support/solutions/articles/65000170065-ledger-error-spec-version-not-supported)
Video on how to update your Ledger apps ✅ --> https://youtu.be/L7PFGEILnF4
- [ ] [Crowdloan page on Polkadot-JS UI explained](https://support.polkadot.network/support/solutions/articles/65000177427-the-crowdloan-page-on-polkadot-js-explained)
- [x] [How to export your JSON backup file](https://support.polkadot.network/support/solutions/articles/65000177677-how-to-export-your-json-backup-file) ✅ --> https://youtu.be/DNU0p5G0Gqc
- [x] [How can I verify what extrinsic I'm signing?](https://support.polkadot.network/support/solutions/articles/65000179161-how-can-i-verify-what-extrinsic-i-m-signing-) ✅ --> https://youtu.be/bxMs-9fBtFk
- [x] [How to Claim and Access the NFT I Received as a Gift?](https://support.polkadot.network/support/solutions/articles/65000180507-how-do-i-access-the-nft-i-received-as-a-gift-)
- [x] [How to create an account in Parity Signer](https://support.polkadot.network/support/solutions/articles/65000180512-how-to-create-an-account-in-parity-signer) ✅ --> https://youtu.be/hgv1R9mPEXw
- [x] [How to create an account in Subkey](https://support.polkadot.network/support/solutions/articles/65000180519-how-to-create-an-account-in-subkey) ✅ --> https://youtu.be/SWfE_EwxgIU
- [x] [How to create an account in the Polkadot-JS (UI)](https://support.polkadot.network/support/solutions/articles/65000180529-how-to-create-an-account-in-the-polkadot-js-ui-) ✅  --> https://youtu.be/DNU0p5G0Gqc
- [x] [How to Vote in Governance](https://support.polkadot.network/support/solutions/articles/65000180836-how-to-vote-in-governance-referenda), [How to Remove Expired Democracy Locks](https://support.polkadot.network/support/solutions/articles/65000181870-how-to-remove-expired-democracy-locks) (perhaps unnecessary with gov 2.0 coming) ✅ --> https://youtu.be/fHLhzrd5t-g
- [x] [Why Have I Stopped Nominating? Staking Limits explained](https://support.polkadot.network/support/solutions/articles/65000180708-why-have-i-stopped-nominating-staking-limits-explained)
[I have more than the minimum bonded but I'm not getting rewards](https://support.polkadot.network/support/solutions/articles/65000181018-i-have-more-than-the-minimum-bonded-but-i-m-not-getting-rewards)
[I have less than the minimum DOT needed for staking](https://support.polkadot.network/support/solutions/articles/65000181716-i-have-less-than-the-minimum-dot-needed-for-staking)
[How to Join Nomination Pools](https://support.polkadot.network/support/solutions/articles/65000181401-how-to-join-nomination-pools)
A single video on staking limits that introduces bags lists and nomination pools ✅ --> https://youtu.be/hIIZRJLrBZA

- [x] [What is Statemint and Statemine and How do I use them?](https://support.polkadot.network/support/solutions/articles/65000181800-what-is-statemint-and-statemine-and-how-do-i-use-them-) ✅ --> https://youtu.be/knNLZEyposM
[How to Teleport DOT or KSM between Statemint or Statemine](https://support.polkadot.network/support/solutions/articles/65000181119-how-to-teleport-ksm-to-or-from-statemine) ✅  --> https://youtu.be/3tE9ouub5Tg
[How to Transfer USDT on Statemine](https://support.polkadot.network/support/solutions/articles/65000181118-how-to-transfer-tether-usdt-on-statemine) ✅  --> https://youtu.be/knNLZEyposM
[How to Withdraw USDT from Bitfinex on Statemine](https://support.polkadot.network/support/solutions/articles/65000181634-how-to-withdraw-usdt-from-bitfinex-on-statemine)
[Using Ledger with Statemine](https://support.polkadot.network/support/solutions/articles/65000180427-using-ledger-with-statemine) ✅  --> https://youtu.be/j0O-KziV9iw
A single video on Statemin* that explains all concepts and also emphasises on **not** sending tokens from Statemin* to exchanges

- [x] [How to Create and Use a Multisig Account](https://support.polkadot.network/support/solutions/articles/65000181826-how-to-create-and-use-a-multisig-account) ✅ -> https://www.youtube.com/watch?v=-cPiKMslZqI (easy with Accounts tab); https://www.youtube.com/watch?v=T0vIuJcTJeQ (advanced, with Extrinsics tab)
