### ISSUE TITLE
Wiki Update - Mega Issue

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#6085]
- [x] Add hrmp channel setup instructions with system chains
- [x] Add the latest features like asset conversion pools to the Asset Hub page
- [x] PJS guide on connecting to Asset Hub ledger app needs update
- [x] More info on Multi-asset treasury and Treasuries of Collectives
- [x] Add info about https://faucet.polkadot.io/
- [x] Update Agile Coretime FAQ with Polkadot content
- [x] Remove Gov1 info on Getting Started page and add delegation feature to "What can I do with my DOT" section
- [x] Update DF note on Grants page
- [x] Add the latest features like asset conversion pools to the Asset Hub page
- [x] Expand on Snowfork content on Bridge Hub page
- [x] learn DOT page references to outdated videos. ontent could be improved
- [ ] Add a guide that shows how to mint NFTs on Asset Hub
- [x] Agile Coretime for Parachians page can benefit from Educhain content
- [x] More info on Account Identity and People chain
- [x] Update Inflation page with recent forum discusssions
- [x] NFT page can have more Polkadot specific content and details about cross chain NFT transfers
- [x] NFT projects page need update - Is Enjin still with us?
- [x] Parachains and its FAQ page needs update after Agile Coretime goes live on Polkadot
- [x] Runtime Upgrades page only references Polkadot. No info on Parachain Runtime upgrades.
- [x] Coretime chain and People chain to the System chains page
- [x] Teleport assets page can improve. Instructions on recovering Trapped Assets can be added
- [x] Add info about PVM
- [x] Is Ledger App developer release section still relevant?
- [x] Node endpoints are outdated for Polkadot and Kusama. System chains node end points need to be listed. 
- [x] Error table is outdated. Has info on technical committee etc.
- [x] Validator docs rehaul
- [x] Add more system chains to metadata explorer. Links to docs of some extrinsics are broken.
- [x] Refresh wallets page and showcase interesting project features
- [x] Add info of which extrinsics can be submitted in each OpenGov Track

...To be updated

**Comment by CrackTheCode016** [comment]
A few more items for now: 

- [x] No mention of ELVES, only parachains protocol.  General parachains protocol rehaul
- [x] Elastic scaling docs probably need a rework soon (there may have been new / more changes to it, as it is close to deployment)
- [x] Add JAM as part of Polkadot direction
- [x] Update light client page to include smoldot/papi, or remove it altogether
- [x] Most comparisons are probably out of date arguably we should even remove them.

**Comment by joepetrowski** [comment]
I think it'd be good to have some prioritization in here. For example, these seem particularly useful to end users:

- Add the latest features like asset conversion pools to the Asset Hub page
- PJS guide on connecting to Asset Hub ledger app needs update
- More info on Multi-asset treasury and Treasuries of Collectives

While these seem like "interesting" but I don't see the effect they really have:

- Add info about PVM
- Update Inflation page with recent forum discussions

**Comment by kopeboy** [comment]
System chains are missing for Kusama in the wiki at https://wiki.polkadot.network/docs/learn-system-chains#overview

**Comment by CrackTheCode016** [comment]
@filippoweb3 @DrW3RK This needs to be re-evaluated; quite a few of these are done, but a few still need doing. It would be better to create separate issues for those specific items IMO.

**Comment by filippoweb3** [comment]
> System chains are missing for Kusama in the wiki at https://wiki.polkadot.network/docs/learn-system-chains#overview

The Polkadot section includes the standard system chains, while the Kusama section contains those chains only on Kusama.

**Comment by CrackTheCode016** [comment]
I have narrowed down this list to include that which has not been done yet: 

- [x] More info on Multi-asset treasury and Treasuries of Collectives - Explained already. Follow up is creating a guide for interacting with them (issue #6168)
- [x] learn DOT page references to outdated videos. ontent could be improved -> https://github.com/w3f/polkadot-wiki/pull/6679
- [x] NFT page can have more Polkadot specific content and details about cross chain NFT transfers -> https://github.com/w3f/polkadot-wiki/pull/6679
- [x] Add info of which extrinsics can be submitted in each OpenGov Track -> https://github.com/w3f/polkadot-wiki/pull/6680
- [x] Add a guide that shows how to mint NFTs on Asset Hub -> this should be covered here: https://wiki.polkadot.network/learn/learn-nft-projects/, and will be revisited.


The most pressing one is probably on collective treasuries and how to utilize them. I would argue that these should be turned into their own respective issues, WDYT @filippoweb3 ?

**Comment by filippoweb3** [comment]
Closing this issue as everything has been addressed. Regarding the guide to mint NFTs, I wouldn't create them because the KodaDOT platform provides good tools for minting and mass minting NFTs. For fungible tokens, we have this guide in the Technical Explainers: https://youtu.be/knNLZEyposM?feature=shared
